#import <CordieriteSpec/CordieriteSpec.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTInvalidating.h>

// Default-inert release builds: the concrete TurboModule
// implementation below is compiled out entirely unless this is a debug build, or the app has
// explicitly opted in via `CORDIERITE_ENABLE_RELEASE` (a preprocessor flag the config plugin's
// `enableInReleaseBuilds` option defines on the *app* target, mirroring `SWIFT_ACTIVE_COMPILATION_CONDITIONS`
// for `CordieriteTurboBridge.swift`). With nothing here, RN's Objective-C runtime class scan never
// finds a "Cordierite" module: `TurboModuleRegistry` lookups on the JS side come back empty, which
// is exactly what root `src/index.ts`'s `noopIfNativeUnavailable` (which delegates to the
// `./noop` implementations) depends on to degrade automatically. Plain `DEBUG=1` is a reliable
// gate for this pod's own generated Debug configuration; custom
// configs other than Debug/Release don't get `DEBUG` and stay inert unless
// `CORDIERITE_ENABLE_RELEASE` is set.
#if DEBUG || CORDIERITE_ENABLE_RELEASE

#if __has_include("Cordierite-Swift.h")
#import "Cordierite-Swift.h"
#elif __has_include(<Cordierite/Cordierite-Swift.h>)
#import <Cordierite/Cordierite-Swift.h>
#else
#error Cordierite's autogenerated Swift header cannot be found. Try rebuilding Pods and verify the pod module name is Cordierite.
#endif

using namespace facebook::react;

@interface RCTNativeCordierite : NativeCordieriteSpecBase <NativeCordieriteSpec, RCTInvalidating> {
  CordieriteTurboBridge *_swift;
}
@end

@implementation RCTNativeCordierite

RCT_EXPORT_MODULE(Cordierite)

- (instancetype)init
{
  if (self = [super init]) {
    _swift = [[CordieriteTurboBridge alloc] init];
    __weak __typeof__(self) weakSelf = self;
    [_swift
        wireEventHandlersWithStateChange:^(NSString *state) {
          [weakSelf emitOnStateChange:@{@"state" : state}];
        }
        messageRaw:^(NSString *raw) {
          [weakSelf emitOnMessage:@{@"rawMessage" : raw}];
        }
        error:^(NSDictionary *payload) {
          NSMutableDictionary *out = [NSMutableDictionary dictionaryWithDictionary:payload];
          if (out[@"code"] == nil) {
            out[@"code"] = @"connection_failed";
          }
          if (out[@"message"] == nil) {
            out[@"message"] = @"Cordierite connection failed.";
          }
          [weakSelf emitOnError:out];
        }
        close:^(NSDictionary *payload) {
          NSMutableDictionary *out = [NSMutableDictionary dictionary];
          id codeVal = payload[@"code"];
          id reasonVal = payload[@"reason"];
          out[@"code"] = codeVal != nil ? codeVal : [NSNull null];
          out[@"reason"] = reasonVal != nil ? reasonVal : [NSNull null];
          [weakSelf emitOnClose:out];
        }];
  }
  return self;
}

- (std::shared_ptr<TurboModule>)getTurboModule:(const ObjCTurboModule::InitParams &)params
{
  return std::make_shared<NativeCordieriteSpecJSI>(params);
}

#pragma mark - NativeCordieriteSpec

- (void)connect:(JS::NativeCordierite::CordieriteConnectOptionsNative &)options
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject
{
  NSMutableDictionary *opts = [@{
    @"ip" : options.ip(),
    @"port" : @(options.port()),
    @"sessionId" : options.sessionId(),
    @"token" : options.token(),
    @"expiresAt" : @(options.expiresAt()),
  } mutableCopy];

  NSString *deviceManufacturer = options.deviceManufacturer();
  if (deviceManufacturer != nil) {
    opts[@"deviceManufacturer"] = deviceManufacturer;
  }
  NSString *deviceModel = options.deviceModel();
  if (deviceModel != nil) {
    opts[@"deviceModel"] = deviceModel;
  }
  NSString *deviceOs = options.deviceOs();
  if (deviceOs != nil) {
    opts[@"deviceOs"] = deviceOs;
  }
  NSString *resumeToken = options.resumeToken();
  if (resumeToken != nil) {
    opts[@"resumeToken"] = resumeToken;
  }
  // Opt-in hardening dev-mode: the bootstrap deep link's separate `pin` param, forwarded from JS.
  // See CordieriteConnectionManager.swift's `resolveTrustedPins` for the trust decision.
  NSString *linkPin = options.linkPin();
  if (linkPin != nil) {
    opts[@"linkPin"] = linkPin;
  }

  [_swift connectWithOptions:opts resolve:resolve reject:reject];
}

- (void)send:(NSString *)message resolve:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  [_swift sendWithMessage:message resolve:resolve reject:reject];
}

- (void)close:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  [_swift closeWithResolve:resolve reject:reject];
}

- (NSString *)getState
{
  return (NSString *)[_swift getState];
}

- (NSDictionary *)getResumeLease
{
  return [_swift getResumeLease];
}

- (void)clearResumeLease
{
  [_swift clearResumeLease];
}

#pragma mark - RCTInvalidating

- (void)invalidate
{
  [_swift invalidate];
}

@end

#endif // DEBUG || CORDIERITE_ENABLE_RELEASE
